### PR TITLE
Update style

### PR DESCRIPTION
**Pull request by Kikobeats**
This closes #3 and #4 as well.

Remove setTimeout logic

screen shot 2016-09-26 at 16 58 47

### CODE REVIEW

**Comment by cmalven** [comment]
Any chance of making some progress on this? We'd like to start implementing this in our workflow but the current styling leaves something to be desired.

**Comment by Kikobeats** [comment]
@cmalven why?

**Comment by Kikobeats** [comment]
@cmalven I released my fork as a different package, check at https://www.npmjs.com/package/bs-pretty-message 👍

**Comment by cmalven** [comment]
Thanks for the update @Kikobeats

**Pull request closed without merging**
